title: Cheap VTubing
description: VTubing doesn't have to be expensive. You can start your VTubing journey with a laptop and free software, assets, and games. You just need to get started.
theme: just-the-docs

url: https://flockychou.github.io/

aux_links:
  Contribute: https://github.com/FlockyChou/flockychou.github.io/issues

callouts:
  warning:
    title: Warning
    color: red

  important:
    title: Important
    color: blue

  note:
    title: Note
    color: purple