title: VTubing Info
description: VTubing doesn't have to be hard. You just need to get started.
theme: just-the-docs

back_to_top: true
back_to_top_text: "Back to top"

url: https://flockychou.github.io/

aux_links:
  Contribute: https://github.com/FlockyChou/flockychou.github.io/issues

callouts:
  warning:
    title: Warning
    color: red

  important:
    title: Important
    color: blue

  note:
    title: Note
    color: purple