title: Cheap VTubing
description: VTubing Can be Cheap and So Can You!
theme: just-the-docs

url: https://flockychou.github.io/

aux_links:
  Template Repository: https://github.com/FlockyChou/flockychou.github.io
