title: Cheap VTubing
description: VTubing doesn't have to be expensive. You can start your VTubing journey with a laptop and free software, assets, and games. You just need to get started.
theme: just-the-docs

url: https://flockychou.github.io/
logo: "/assets/images/cheap-vtubing-logo.png"

aux_links:
  Contribute: https://github.com/FlockyChou/flockychou.github.io/issues
